[package]
name = "sam"
description = "Steam Achievement Manager"
version = "2.0.3"
repository = "https://github.com/mbwilding/steam-achievement-manager"
edition = "2024"
license-file = "LICENSE"
readme = "README.md"
build = "build.rs"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
confy = "2.0.0"
crossterm = "0.29.0"
gag = "1.0.0"
openssl = { version = "0.10.81", features = ["vendored"] }
ratatui = "0.30.1"
serde = { version = "1.0.228", features = ["derive"] }
steamworks = "0.13.1"

[build-dependencies]
glob = "0.3.3"

[profile.release]
opt-level = "z"         # Optimize for size.
lto = true              # Enable Link Time Optimization.
codegen-units = 1       # Reduce the number of codegen units to enhance optimization.
strip = true            # Remove symbol information for a smaller binary.
panic = "abort"         # Aborts on panic, reducing the binary size.
incremental = false     # Disable incremental compilation.
overflow-checks = false # Disable overflow checks if not required (unsafe).

[profile.dev.package."*"]
opt-level = 2
