name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os:
          - runtime: linux-x64
          - runtime: win-x64
          - runtime: osx-x64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dotnet
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: 9.0.x

      - name: Build
        shell: bash
        run: |
          # Instead of passing --os and --arch which set a RuntimeIdentifier on the solution build,
          # run the build first without a RID, then publish per project with the specific RID from the matrix.
          dotnet build --configuration Release
          # Example publishing for a specific project (replace "YourProject.csproj" with the appropriate project name)
          dotnet publish "YourProject.csproj" --configuration Release --runtime ${{ matrix.os.runtime }} --self-contained false

      - name: List Build Artifacts
        run: |
          pushd Build
          ls
          popd
