name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: linux
            arch: x64
          - os: win
            arch: x64
          - os: osx
            arch: x64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dotnet
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: 9.0.x

      - name: Build
        run: |
          dotnet build "SteamAchievementUnlocker/SteamAchievementUnlocker.csproj" --configuration Release --os ${{ matrix.os }} --arch ${{ matrix.arch }}
          dotnet build "SteamAchievementUnlockerAgent/SteamAchievementUnlockerAgent.csproj" --configuration Release --os ${{ matrix.os }} --arch ${{ matrix.arch }}
          find "Build/Release/net9.0/${{ matrix.os }}-${{ matrix.arch }}/runtimes" -mindepth 1 -maxdepth 1 -type d ! -name "${{ matrix.os }}-${{ matrix.arch }}*" -exec rm -rf {} +

      - name: Zip
        run: |
          pushd "Build/Release/net9.0/${{ matrix.os }}-${{ matrix.arch }}"
          zip -r "SteamAchievementUnlocker-${{ matrix.os }}-${{ matrix.arch }}.zip" .
          popd

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: Build/Release/net9.0/${{ matrix.os }}-${{ matrix.arch }}/SteamAchievementUnlocker-${{ matrix.os }}-${{ matrix.arch }}.zip
          name: SteamAchievementUnlocker-${{ matrix.os }}-${{ matrix.arch }}.zip

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: '**/SteamAchievementUnlocker-*.zip'
          merge-multiple: true
          path: .

      - name: Create Git Tag
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git tag -a ${{ github.run_number }} -m "${{ github.run_number }}"
          git push origin ${{ github.run_number }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.run_number }}
          release_name: ${{ github.run_number }}
          files: |
            *.zip
