name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: linux
            arch: x64
            binary: libsteam_api.so
          - os: win
            arch: x64
            binary: steam_api64.dll
          - os: osx
            arch: x64
            binary: libsteam_api.dylib
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dotnet
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: 9.0.x

      - name: Build
        shell: bash
        run: |
          dotnet build "SteamAchievementUnlocker/SteamAchievementUnlocker.csproj" --configuration Release --os ${{ matrix.os }} --arch ${{ matrix.arch }}
          dotnet build "SteamAchievementUnlockerAgent/SteamAchievementUnlockerAgent.csproj" --configuration Release --os ${{ matrix.os }} --arch ${{ matrix.arch }}
          base_path="Build/Release/net9.0/${{ matrix.os }}-${{ matrix.arch }}/runtimes"
          lib_path="${base_path}/${{ matrix.os }}-${{ matrix.arch }}/lib/netstandard2.1"
          dep_path="Common/runtimes/${{ matrix.os }}-${{ matrix.arch }}/lib/netstandard2.1"

          echo "dep_path: $dep_path"
          ls "$dep_path"

          find "$base_path" -mindepth 1 -maxdepth 1 -type d ! -name "${{ matrix.os }}-${{ matrix.arch }}*" -exec rm -rf {} +
          cp "${dep_path}/${binary}" "$lib_path"

          echo "lib_path: $lib_path"
          ls "$lib_path"

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Test"

      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: |
      #       *.zip
      #     name: ${{ github.run_number }}
      #     tag_name: ${{ github.run_number }}
