name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [linux, windows, macos]
        arch: [x64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dotnet
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: 9.0.x

      - name: Build
        shell: bash
        run: |
          dotnet build --configuration Release --arch ${{ matrix.arch }} --os ${{ matrix.os }}
          pushd Build
          ls

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Test"

      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: |
      #       *.zip
      #     name: ${{ github.run_number }}
      #     tag_name: ${{ github.run_number }}
