name: Release

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: 9.0

jobs:
  build:
    strategy:
      matrix:
        os: [linux, win, osx]
        arch: [x64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dotnet
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: ${DOTNET_VERSION}.x

      - name: Build
        shell: bash
        run: |
          dotnet build "SteamAchievementUnlocker/SteamAchievementUnlocker.csproj" --configuration Release --os ${{ matrix.os }} --arch ${{ matrix.arch }}
          dotnet build "SteamAchievementUnlockerAgent/SteamAchievementUnlockerAgent.csproj" --configuration Release --os ${{ matrix.os }} --arch ${{ matrix.arch }}
          ls Build/Release/net${DOTNET_VERSION}/${{ matrix.os }}-${{ matrix.arch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Test"

      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: |
      #       *.zip
      #     name: ${{ github.run_number }}
      #     tag_name: ${{ github.run_number }}
