name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [linux, win, osx]
        arch: [x64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dotnet
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: 9.0.x

      - name: Build
        shell: bash
        run: |
          dotnet build "SteamAchievementUnlocker/SteamAchievementUnlocker.csproj" --configuration Release --os ${{ matrix.os }} --arch ${{ matrix.arch }}
          dotnet build "SteamAchievementUnlockerAgent/SteamAchievementUnlockerAgent.csproj" --configuration Release --os ${{ matrix.os }} --arch ${{ matrix.arch }}
          lib_path="Build/Release/net9.0/${{ matrix.os }}-${{ matrix.arch }}/runtimes/${{ matrix.os }}-${{ matrix.arch }}/lib/netstandard2.1"
          find "Build/Release/net9.0/${{ matrix.os }}-${{ matrix.arch }}/runtimes" -mindepth 1 -maxdepth 1 -type d ! -name "${{ matrix.os }}-${{ matrix.arch }}*" -exec rm -rf {} +
          cp "Common/runtimes/${{ matrix.os }}-${{ matrix.arch }}/lib/netstandard2.1/libsteam_api.*" "$lib_path"
          ls "$lib_path"

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Test"

      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: |
      #       *.zip
      #     name: ${{ github.run_number }}
      #     tag_name: ${{ github.run_number }}
