name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      shell: bash
      run: |
        dotnet build --configuration Release
        pushd Build
        ls

    # - name: Release
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     files: |
    #       *.zip
    #     name: ${{ github.run_number }}
    #     tag_name: ${{ github.run_number }}
