name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Output Run ID
      run: |
        echo "run_id: ${{ github.run_id }}"
        echo "run_number: ${{ github.run_number }}"

    # - name: Release
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     files: |
    #       *.zip
    #     name: ${{ steps.version.outputs.version }}
    #     tag_name: ${{ steps.version.outputs.version }}
